name: deploy
on: [push, workflow_dispatch]
permissions:
  pages: write
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.d.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - name: build site
        run: |
          mkdir site
          cp index.html model.meta.json scene_extra.json site/
          cd site
          curl -fL "https://drive.usercontent.google.com/download?id=1QP41CeERfrjrjPKwaER0CLoU6WTQ3zU7&export=download&confirm=t" -o model-cfc5c292.p0.wasm
          curl -fL "https://drive.usercontent.google.com/download?id=1Cspzu-AVHyxEkszMsdY-CVoozheJQcfA&export=download&confirm=t" -o model-cfc5c292.p1.wasm
          curl -fL "https://drive.usercontent.google.com/download?id=1cpb6W-N-TxG4WxT0D6iCQaMp5wMz7I6Z&export=download&confirm=t" -o model-cfc5c292.p2.wasm
          touch .nojekyll
          ls -la
      - uses: actions/configure-pages@v5
        with:
          enablement: true
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - id: d
        uses: actions/deploy-pages@v4
